import sys
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QApplication

from presenter.presenter import Presenter

# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(695, 524)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         font = QtGui.QFont()
#         font.setPointSize(30)
#         self.label.setFont(font)
#         self.label.setAlignment(QtCore.Qt.AlignCenter)
#         self.label.setObjectName("label")
#         self.verticalLayout.addWidget(self.label)
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
#         self.graphicsView_2.setObjectName("graphicsView_2")
#         self.horizontalLayout.addWidget(self.graphicsView_2)
#         self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
#         self.graphicsView_3.setObjectName("graphicsView_3")
#         self.horizontalLayout.addWidget(self.graphicsView_3)
#         self.verticalLayout.addLayout(self.horizontalLayout)
#         self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
#         self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.checkBox.setObjectName("checkBox")
#         self.verticalLayout.addWidget(self.checkBox)
#         self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_3.setObjectName("horizontalLayout_3")
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setObjectName("label_2")
#         self.horizontalLayout_3.addWidget(self.label_2)
#         self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
#         self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
#         self.horizontalSlider.setObjectName("horizontalSlider")
#         self.horizontalLayout_3.addWidget(self.horizontalSlider)
#         self.verticalLayout.addLayout(self.horizontalLayout_3)
#         self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_5.setObjectName("horizontalLayout_5")
#         self.label_4 = QtWidgets.QLabel(self.centralwidget)
#         self.label_4.setObjectName("label_4")
#         self.horizontalLayout_5.addWidget(self.label_4)
#         self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
#         self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
#         self.horizontalSlider_3.setObjectName("horizontalSlider_3")
#         self.horizontalLayout_5.addWidget(self.horizontalSlider_3)
#         self.verticalLayout.addLayout(self.horizontalLayout_5)
#         self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_6.setObjectName("horizontalLayout_6")
#         self.label_5 = QtWidgets.QLabel(self.centralwidget)
#         self.label_5.setObjectName("label_5")
#         self.horizontalLayout_6.addWidget(self.label_5)
#         self.horizontalSlider_4 = QtWidgets.QSlider(self.centralwidget)
#         self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
#         self.horizontalSlider_4.setObjectName("horizontalSlider_4")
#         self.horizontalLayout_6.addWidget(self.horizontalSlider_4)
#         self.verticalLayout.addLayout(self.horizontalLayout_6)
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setObjectName("pushButton")
#         self.verticalLayout.addWidget(self.pushButton)
#         self.verticalLayout_2.addLayout(self.verticalLayout)
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 21))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.label.setText(_translate("MainWindow", "Pandemiesimulator"))
#         self.checkBox.setText(_translate("MainWindow", "People staying at home"))
#         self.label_2.setText(_translate("MainWindow", "Parameter 1"))
#         self.label_4.setText(_translate("MainWindow", "Parameter 1"))
#         self.label_5.setText(_translate("MainWindow", "Parameter 1"))
#         self.pushButton.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setStyle('Fusion')

    presenter = Presenter()
    presenter.ui.show()

    sys.exit(app.exec_())

    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # MainWindow = QtWidgets.QMainWindow()
    # ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    # MainWindow.show()
    # sys.exit(app.exec_())